### ISSUE TITLE
Incompatible with LibertyBans muting

### ISSUE THREAD

**Issue by Madscience763** [confor/velocity-chat#3]
Muting a player using LibertyBans will not work with global chat enabled

**Comment by confor** [comment]
makes sense, since the chat is handled by the proxy instead of bukkit/spigot plugins.

a quick google search shows that libertybans has a velocity build, did you try that one? maybe it will cancel the chat events before this plugin.

**Comment by Madscience763** [comment]
I am using the velocity version.

**Comment by BBaoVanC** [comment]
The chat listener in this plugin is set to run with highest priority (see https://github.com/confor/velocity-chat/blob/bb3a43cd3725b1244999e5660eafbfbfe7021aa3/src/main/java/me/confor/velocity/chat/modules/GlobalChat.java#L47), but I'm not sure why. Is there any reason it can't run with normal or late priority?
